export default {
    secretKey: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5ODMzNDI1NywiaWF0IjoxNjk4MzM0MjU3fQ.qvVRJrl0WlIoAsRWOhqhvir3dfpnC9Zc5cqHGjUIgWU'
}